<?php
         $validid=file_get_contents("inc/security/i.php");
         $validpass=file_get_contents("inc/security/p.php");
         $enclogeduserid=$_SESSION[id];
         $enclogeduserpass=$_SESSION[pass];
         $sc=$_SESSION[sc];
         $submit=$_POST[login];

         if(($validid==$enclogeduserid)&&($validpass==$enclogeduserpass))
         {
           include("inc/db.php");
		   connect_database();
         }
         elseif($submit)
         {
			$userid=htmlentities($_POST[id]);
			$userpass=htmlentities($_POST[pass]);
           if($userid&&$userpass)
           {
			$encuserid=md5($userid);
			$encuserpass=md5($userpass);
             if(($validid==$encuserid)&&($validpass==$encuserpass))
             {
               $_SESSION[id]=$encuserid;
               $_SESSION[pass]=$encuserpass;
               $_SESSION[sc]=0;
			   $sc=0;
               include("inc/db.php");
			   connect_database();
             }
             else
             {
               $logerror=3;
               include("inc/loginform.php");
               die();
             }
           }
           else
           {
             $logerror=2;
             include("inc/loginform.php");  
             die();
           }
         }
         else
         {
            $logerror=1;
            include("inc/loginform.php");  
            die();
         }
?>